### ISSUE TITLE
Can't receive incoming calls

### ISSUE THREAD

**Issue by MahMaejah** [frappe/twilio-integration#33]
Incoming calls are not working. How do I configure this for incoming calls

**Comment by asoral** [comment]
How did you get this to work? @chipohameja

**Comment by alperengunes** [comment]
You need to create a [new project](https://www.twilio.com/console/projects/create) in [Twilio account](https://www.twilio.com/) to use communication features like whatsapp, voice calls etc through ERPNext.
From your Twilio console you can go to a [programmable voice](https://www.twilio.com/console/voice/dashboard) section and get a Twilio number to use for calls(make sure that the number is voice capable).
Create a [TwiML App](https://www.twilio.com/console/voice/twiml/apps/create) by passing voice request url as <your_site>/api/method/twilio_integration.twilio_integration.api.voice . Use ngrok to get public domain for your project in case it is running locally.
For incoming calls to work, you will have to go to Active Number (https://console.twilio.com/us1/develop/phone-numbers/manage/incoming)
Select the number you need to use for incoming
Select Webhook, TwiML Bin, .... in "Configure with" field under the "Configure" tab
Select "Webhook" in "A call comes in" field
Set URL > <site_url>/api/method/twilio_integration.twilio_integration.api.twilio_incoming_call_handler
