### ISSUE TITLE
No outgoing whatsApp notification/message from ERPnext 

### ISSUE THREAD

**Issue by deepakc21** [frappe/twilio-integration#40]
Issue: No outgoing whatsApp notification/message from ERPnext 

Steps to reproduce the bug:
1. Click on 'Purchase Invoice' in the "Buying" module.
2. Click on 'Add Purchase invoice'.
3. Enter details and Submit the invoice.

Actual result:
The purchase invoice is submitted but no whatsapp message is sent to the "supplier" phone number.

**Note:
1) Twilio account configured and whatsapp templates approved.
![wp](https://user-images.githubusercontent.com/97949896/191180940-24679cc6-c0c1-4d2e-9ec8-7ff4823847aa.jpg)
2) Twilio settings and communication channel configured in EPRnext system.
![wp3](https://user-images.githubusercontent.com/97949896/191181035-98430e0b-e588-4f58-87e5-8bb4e2fd8731.jpg)
![wp4](https://user-images.githubusercontent.com/97949896/191181049-77e2f924-d11c-4aa6-9eef-8843e8ded822.jpg)
3) Notification created in EPRnext.
![wp2](https://user-images.githubusercontent.com/97949896/191181138-2a492442-d529-447b-a6dc-0e1ece2c0494.jpg)
![wp1](https://user-images.githubusercontent.com/97949896/191181172-5822f370-f43c-43f9-ae92-264eee18686f.jpg)

**Comment by deepakc21** [comment]
**Error log info**
Title: Failed to send notification
Error: Traceback (most recent call last):
  File "apps/twilio_integration/twilio_integration/twilio_integration/doctype/whatsapp_message/whatsapp_message.py", line 19, in send
    response = client.messages.create(**message_dict)
  File "env/lib/python3.10/site-packages/twilio/rest/api/v2010/account/message/__init__.py", line 89, in create
    payload = self._version.create(method='POST', uri=self._uri, data=data, )
  File "env/lib/python3.10/site-packages/twilio/base/version.py", line 204, in create
    raise self.exception(method, uri, response, 'Unable to create record')
twilio.base.exceptions.TwilioRestException: HTTP 400 error: Unable to create record: The 'To' number whatsapp:None is not a valid phone number.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/twilio_integration/twilio_integration/overrides/notification.py", line 26, in send
    self.send_whatsapp_msg(doc, context)
  File "apps/twilio_integration/twilio_integration/overrides/notification.py", line 33, in send_whatsapp_msg
    WhatsAppMessage.send_whatsapp_message(
  File "apps/twilio_integration/twilio_integration/twilio_integration/doctype/whatsapp_message/whatsapp_message.py", line 51, in send_whatsapp_message
    message.send()
  File "apps/twilio_integration/twilio_integration/twilio_integration/doctype/whatsapp_message/whatsapp_message.py", line 28, in send
    frappe.log_error(e, title = _('Twilio WhatsApp Message Error'))
TypeError: log_error() got multiple values for argument 'title'

**Comment by deepakc21** [comment]
Hello,

Please help me in understanding the correct value for “Receiver by Document field” and “Receiver by role” fields so that the phone number can be captured correctly.  tried the options given in the “Receiver by Document field” and “Receiver by role” fields but the “Phone number” is not getting captured in “To whatsapp number” field. I have provided the contact information in supplier details also. 
![1](https://user-images.githubusercontent.com/97949896/193558407-3ad50c81-0487-4b0c-833a-f4b704be1eda.jpeg)

**Comment by deepakc21** [comment]
The field “To whatsApp number” is not taking any value.
![1](https://user-images.githubusercontent.com/97949896/194690793-dd57ad8f-9fc0-4918-8d32-f7ea8cfe88c6.jpeg)

**Comment by deepakc21** [comment]
Hello, 
Please, can anyone help with the issue here.

**Comment by deepakc21** [comment]
Hello,
Please help with the issue here.

**Comment by deepakc21** [comment]
Hello, Please anyone can look into this issue.

**Comment by DataSoft2022** [comment]
Dears any help here

**Comment by deepakc21** [comment]
Closing this bug as the solution has been provided on EPRnext forum. Link - https://discuss.erpnext.com/t/no-outgoing-whatsapp-notification-message-from-erpnext/95064/13
